### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by taoeffect** [gmazovec/flow-typer#1]
Yo just wanted to say thanks for making this and keeping it at 0 dependencies! It looks like exactly what I need. Haven't tried it out yet but plan to!

**Comment by gmazovec** [comment]
I'm glad to hear that. I would be thankful for your feedback once you start
using it.

**Comment by gmazovec** [comment]
I'm glad to hear that. I would be thankful for your feedback once you start using it.

**Comment by taoeffect** [comment]
Feedback now that I've started using it:

It's great! Just as I expected it's perfect for our use case. You did a wonderful job. 👍

**Comment by taoeffect** [comment]
@gmazovec Some more feedback: we're using a modified version of this library here in case you'd like to see the modifications we made: https://github.com/okTurtles/group-income/blob/d5d3267fa6c5755559e00b7f348f317c81969444/frontend/model/contracts/misc/flowTyper.js

**Comment by gmazovec** [comment]
@taoeffect This commit adds the re-exports 6ad14a8 . The rollup should probably use exports for main file.
