### ISSUE TITLE
What's equivalent to { foo?: mixed } ?

### ISSUE THREAD

**Issue by wips** [gmazovec/flow-typer#2]
First of all - thanks a lot for such a great tool! Really helpful, removes a lot of code!

My question is how to annotate an object with an optional field?

```js
// in flow notation
type T1 = { foo?: mixed };

// in flow-typer notation
const schemaT1v1 = objectOf({ foo: maybe(mixed) });
const schemaT1v2 = objectOf({ foo: optional(mixed) });
```
Neither of `schemaT1v1` and `schemaT1v2` do the job when field isn't in the object. Both fail object validation. It is expected, because they are equivalents of `{ foo: ?mixed }`. So the question is if there're equivalent for `T1` like type?

P. S. I understand that an object with optional field on the type-checker level is basically the same as a non-sealed object without such field at all, but maybe there's a way to annotate such field in flow-typer? It is needed just as a documentation for the code. 

P.P.S. Btw, what is the difference between `optional` and `maybe`?

**Comment by gmazovec** [comment]
@wips What's you example? I don't understand why validation fails in your case.

```js
type T1 = { foo?: mixed }
// equivalent to
const schemaT1 = objectOf({ foo: optional(mixed) })
```

**Comment by wips** [comment]
@gmazovec, ok, let me provide a simplified example. This is the code:
```js
// @flow

const { objectOf, optional, string } = require('flow-typer-js');

type DesiredType = {
  constantField: string,
  optionalField?: string,
};

const schema = objectOf({
  constantField: string,
  optionalField: optional(string),
});

type TyperType = $Call<typeof schema>;

const a: DesiredType = { constantField: 'foo' };
const b: TyperType = { constantField: 'foo' };
```

This is flow check output:
```sh
$ node node_modules/flow-bin/cli.js check src/foo.js
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/foo.js:18:22

Cannot assign object literal to b because property optionalField is missing in object literal [1] but exists in object
type [2].

        15│ type TyperType = $Call<typeof schema>;
        16│
        17│ const a: DesiredType = { constantField: 'foo' };
 [2][1] 18│ const b: TyperType = { constantField: 'foo' };
        19│



Found 1 error
```
So, in your words:
```js
const schemaT1 = objectOf({ foo: optional(mixed) })
// equivalent to
type T1 = { foo: ?mixed }
// but not equivalent to
type T2 = { foo?: mixed }
```
Hope it clarifies my issue.

**Comment by gmazovec** [comment]
You're right. Unfortunately it's not possible to infer this kind of type for validator.

Validation will work as expected at runtime. So what you can do is to avoid using `type TyperType` in this case and cast type with `type DesiredType`.

**Comment by wips** [comment]
Both `DesiredType` and `TyperType` are just examples. Ideally I want to have only `TyperType`, not to repeat myself. Al least, now I'm sure that what I want is impossible and I'm not missing anything. Thank you!
