### ISSUE TITLE
Is it possible to describe non-exact object types?

### ISSUE THREAD

**Issue by wips** [gmazovec/flow-typer#3]
`objectOf({ foo: Bar })` generates an exact object type (i.e. `{| foo: Bar |}`), is it possible to generate non exact object type (i.e. `{ foo: Bar }`)?

**Comment by gmazovec** [comment]
You can only define non-exact object type with _flow_. I'm using flow's `$ObjMap` utility type which returns exact object type. I guess _flow_ follows consistency with literal object type inferring.

```js
const type = { name: 'foo' } // => type {| name: string |}
```

Using exact type is preferred as it adds more strictness. If you want to omit some properties in object use `optional` type.

**Comment by wips** [comment]
I agree about strictness. But in our case, we receive a huge objects from external APIs and we only need 4-6 fields from dozens. Creating a description for all those fields is too expensive for us. So, my question is if it is possible to implement non-exact object types? If yes I'm willing to make such a contribution.

**Comment by gmazovec** [comment]
I don't see a way to infer non-exact object type from JavaScript.

In your case there's simple workaround. Pick properties from original object that you need and then do the validation.

```js
const huge = { ... }
const sparse = pick(huge, [...])
const validated = schema(sparse)
```

**Comment by wips** [comment]
Ok thanks for the answer.

Regarding the workaround. I have deeply nested objects (3-4 levels deep) and picking fields from them basically equals to manual type refinement - I still need to check all non-last-level fields to be objects/arrays. After all those checks are done most of the work regarding structure checking is already done.

Anyway thanks, I'll think of the solution some more time and notify if I have smth.
