### ISSUE TITLE
Maybe type is not working with undeclared properties

### ISSUE THREAD

**Issue by vpanichkin** [gmazovec/flow-typer#4]
**Steps to Reproduce:**

1. Create schema

```
const stringFieldObjectSchema = objectOf({
  someField1: string,
  someField2: string
});

const schema = objectOf({ 
  someMaybeField: maybe(stringFieldObjectSchema)
});
```
2. Use schema as 
```
const result = schema({});
```

The problem is that we cannot pass object with undeclared variable, regardless of undeclared field has undefined value. So we cannot use it JS explicitly and need to set field as undefined
`schema({someMaybeField: undefined});`
```
Current error when no field declared:
[TypeValidatorError: empty object property 'someMaybeField' for Object.body type 
        file     some-file.js:13:10
        scope    Object.body.someMaybeField
        expected void | null | ({| someField1: string, someField2: string |})
        type     -
        value    undefined
]]]
```
Expected Result:
Field represented as `maybe` object can be undeclared

**Comment by vpanichkin** [comment]
UPD: There is no problems with undeclared optional, but, as develop I need optional + null value

**Comment by gmazovec** [comment]
Hi Viktor! Your solution is what _optional_ validator is using internally and it just a shortcut for _unionOf_.

```
type Schema = {
  someMaybeField?: ?string
};
```

```js
const schema = objectOf({
  someMaybe: optional(maybe(string))
})
```
